<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-98LH4AI" failures="0" tests="3" name="com.testng.org.Exception_Test" time="0.022" errors="0" timestamp="04 Mar 2021 04:39:39 GMT" skipped="0">
  <testcase classname="com.testng.org.Exception_Test" name="add" time="0.018"/>
  <testcase classname="com.testng.org.Exception_Test" name="multiplication" time="0.002"/>
  <testcase classname="com.testng.org.Exception_Test" name="divide" time="0.002"/>
</testsuite> <!-- com.testng.org.Exception_Test -->
